
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/verifyhub?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=verifyhub_user
spring.datasource.password=VerifyHub@2026Strong
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security=DEBUG
logging.level.com.pragyan.verifyhub=DEBUG

app.jwt.secret=ThisIsAVeryLongSecretKeyForVerifyHubProjectMustBeAtLeast256BitsLongForHS256SoMakeItLongerThanItSeemsNecessary
app.jwt.expiration-ms=86400000